# Tratamento relatório Blink

1) Função para extrair o valor do plano da imagem

In [2]:
import requests
import base64
import re
import pandas as pd
import numpy as np

# Chave API Google - Pessoal Rangel
API_KEY = "AIzaSyA2QBWsoOKBIAg7gdp-OL2JqbK_TS3iXoU"

import re

def extrair_valor_plano(texto):
    if not isinstance(texto, str):
        return None

    # Normalizar
    texto = texto.replace("\n", "")
    texto = texto.replace(" ", "")
    # Corrigir padrões quebrados tipo 129,0,00
    texto = texto.replace(",0,00", ",00")
    # Extrair valores monetários com 2 casas
    matches = re.findall(r"\d+[.,]\d{2}", texto)
    if not matches:
        return None
    # Converter para float
    valores = [float(v.replace(",", ".")) for v in matches]
    # Regra: menor valor normalmente é o preço final
    return min(valores)

def extrair_preco_imagem(url_imagem):
    try:
        # 1️⃣ Baixar imagem
        headers = {"User-Agent": "Mozilla/5.0"}
        img_response = requests.get(url_imagem, headers=headers, timeout=10)
        img_response.raise_for_status()
        imagem_base64 = base64.b64encode(img_response.content).decode()
        # 2️⃣ Enviar para Vision API
        endpoint = f"https://vision.googleapis.com/v1/images:annotate?key={API_KEY}"
        payload = {
            "requests": [
                {
                    "image": {"content": imagem_base64},
                    "features": [{"type": "TEXT_DETECTION"}]
                }
            ]
        }
        response = requests.post(endpoint, json=payload, timeout=10)
        response.raise_for_status()
        data = response.json()
        if "fullTextAnnotation" not in data["responses"][0]:
            return None
        texto = data["responses"][0]["fullTextAnnotation"]["text"]
        saida =extrair_valor_plano(texto)
        return saida

    except Exception as e:
        print(f"Erro: {e}")
        return None
    
# Obtenção
df_img = pd.read_csv("../../data/scraped/blink.csv")
df_img = df_img[["URL_IMAGEM"]].drop_duplicates()
df_img["PRECO"] = df_img["URL_IMAGEM"].apply(extrair_preco_imagem)
df_img

                                           URL_IMAGEM  PRECO
0   https://www.blinktelecom.com.br/wp-content/upl...  149.0
1   https://www.blinktelecom.com.br/wp-content/upl...  139.0
2   https://www.blinktelecom.com.br/wp-content/upl...  139.0
3   https://www.blinktelecom.com.br/wp-content/upl...  178.0
4   https://www.blinktelecom.com.br/wp-content/upl...   99.0
5   https://www.blinktelecom.com.br/wp-content/upl...  129.0
6   https://www.blinktelecom.com.br/wp-content/upl...  129.0
7   https://www.blinktelecom.com.br/wp-content/upl...  114.0
10  https://www.blinktelecom.com.br/wp-content/upl...  129.0

2. Tratamento dos dados

In [3]:
# Obtenção
df = pd.read_csv("../../data/scraped/blink.csv")

# Renomeando colunas
df = df.rename(columns={"data_coleta": "DATA"})

# Código dos municípios
de_para_cod_municipio = {"Belo Horizonte": 3106200,
                         "Betim": 3106705,
                         "Ribeirão das Neves": 3154606,
                         "Santa Luzia": 3157807,
                         "Vespasiano": 3171204,
                         "Contagem": 3118601}

# Add coluna COD_MUNICIPIO
df["COD_MUNICIPIO"] = df["MUNICIPIO"].map(de_para_cod_municipio)
if df["COD_MUNICIPIO"].isna().any():
    print("🟠 Há municípios não listados no de-para!")

# Add coluna de OBS
df["OBS"] = df["TITULO"] + "/" + df["MUNICIPIO"] + "/" + df["URL_IMAGEM"]

# Ajustando velocidade
df["VALOR_VELOCIDADE"] = df["VELOCIDADE"].astype(str).str.extract(r"(\d+)").astype("Int64")
df["VELOCIDADE"] = np.where(df["VELOCIDADE"].str.contains("GIGA", case=False, na=False),
                              df["VALOR_VELOCIDADE"]*1000,
                              df["VALOR_VELOCIDADE"] )

# Add coluna de ID
df["ISP"] = "Blink"
df["ID"] = df["ISP"].astype(str) + "_" + df["DATA"] + "_" + (df.index + 1).astype(str)

# Add PRECO
df = df.merge(
    df_img[["URL_IMAGEM", "PRECO"]],
    on="URL_IMAGEM",
    how="left"
)

# SVA
df["SVAs"] = df["TITULO"].str.split("+").str[1:].apply(lambda lst: [re.sub(r"\s+", " ", x).strip() for x in lst]).str.join(", ")

# Add coluna adiconais
df["PERIODO"] = pd.NA
df["PRECO_DEPOIS"] = pd.NA

df = df[["ID", "DATA", "ISP", "VELOCIDADE",
         "SVAs",
         "PRECO",
         "PERIODO", "PRECO_DEPOIS", "COD_MUNICIPIO", "OBS"]]

# Salvando
nome_arq = df["DATA"].max() + "-BLINK.csv"
pasta = r"\\fileserver\arquivos\Estrategia Comercial\2. POWER BI\ECM - Radar Mercado\ScrapingPlanos"
df.to_csv(fr"{pasta}\{nome_arq}", index=False)
print(f"🟢 {nome_arq} salvo!")

df

🟢 2026-03-17-BLINK.csv salvo!

,ID,DATA,ISP,VELOCIDADE,SVAs,PRECO,PERIODO,PRECO_DEPOIS,COD_MUNICIPIO,OBS
0,Blink_2026-03-17_1,2026-03-17,Blink,600,Premiere,149.0,<NA>,<NA>,3106200,600 MEGA + Premiere/Belo Horizonte/https://www...
1,Blink_2026-03-17_2,2026-03-17,Blink,800,,139.0,<NA>,<NA>,3106200,800 MEGA/Belo Horizonte/https://www.blinktelec...
2,Blink_2026-03-17_3,2026-03-17,Blink,1000,,139.0,<NA>,<NA>,3106200,1 GIGA/Belo Horizonte/https://www.blinktelecom...
3,Blink_2026-03-17_4,2026-03-17,Blink,1000,,178.0,<NA>,<NA>,3106200,1 GIGA MESH/Belo Horizonte/https://www.blinkte...
4,Blink_2026-03-17_5,2026-03-17,Blink,600,,99.0,<NA>,<NA>,3106200,600 MEGA/Belo Horizonte/https://www.blinktelec...
...,...,...,...,...,...,...,...,...,...,...
61,Blink_2026-03-17_62,2026-03-17,Blink,1000,,139.0,<NA>,<NA>,3171204,1 GIGA/Vespasiano/https://www.blinktelecom.com...
62,Blink_2026-03-17_63,2026-03-17,Blink,1000,,178.0,<NA>,<NA>,3171204,1 GIGA MESH/Vespasiano/https://www.blinkteleco...
63,Blink_2026-03-17_64,2026-03-17,Blink,600,,99.0,<NA>,<NA>,3171204,600 MEGA Norte/Vespasiano/https://www.blinktel...
64,Blink_2026-03-17_65,2026-03-17,Blink,800,dISNEY,129.0,<NA>,<NA>,3171204,800 MEGA + dISNEY/Vespasiano/https://www.blink...
65,Blink_2026-03-17_66,2026-03-17,Blink,800,HBO Max,129.0,<NA>,<NA>,3171204,800 MEGA + HBO Max/Vespasiano/https://www.blin...