# **Scraping Planos Ouronet**

_Página do provedor: https://ouronet.com.br/cidade/ouro-branco/_

In [1]:
# Bibliotecas
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup
from datetime import date
import re

## **1. Extração**

In [3]:
# Obter lista de planos
texto_html = open("../../data/scraped/ouronet.html", encoding="utf-8")
soup = BeautifulSoup(texto_html, "html.parser")
planos = soup.select(
    "div.slick-slide"
)
                       #attrs={"data-elementor-type": "jet-listing-items"})
print(f"{len(planos)} cartões de planos capturados.")

16 cartões de planos capturados.

In [4]:
# Obter informações do plano
def raspar_plano(plano):
    descricao = " ".join(
        h2.text.strip() for h2 in plano.find_all("h2")
        )
    imgs = plano.find_all("img")
    svas_urls = list({img.get("src") for img in imgs if img.get("src")})

    return {"descricao": descricao,
            "svas": svas_urls}

dados = []

for i in planos:
    try:
        dados_plano = raspar_plano(i)
        dados.append(dados_plano)
    except Exception as e:
        continue

df = pd.DataFrame(dados)
df

,descricao,svas
0,"600 Mb por apenas R$15,00 no combo! 109,90",[https://ouronet.com.br/wp-content/webp-expres...
1,"+VENDIDO 300 Mb 99,90",[https://ouronet.com.br/wp-content/webp-expres...
2,80 Mb + bônus de 20 Mb *apenas na contratação ...,[https://ouronet.com.br/wp-content/webp-expres...
3,40 Mb + bônus de 20 Mb *apenas na contratação ...,[https://ouronet.com.br/wp-content/webp-expres...
4,"800 Mb 164,90",[https://ouronet.com.br/wp-content/webp-expres...
5,"800 Mb por apenas R$10,00 no combo! 129,90",[https://ouronet.com.br/wp-content/webp-expres...
6,"600 Mb por apenas R$15,00 no combo! 109,90",[https://ouronet.com.br/wp-content/webp-expres...
7,"+VENDIDO 300 Mb 99,90",[https://ouronet.com.br/wp-content/webp-expres...
8,80 Mb + bônus de 20 Mb *apenas na contratação ...,[https://ouronet.com.br/wp-content/webp-expres...
9,40 Mb + bônus de 20 Mb *apenas na contratação ...,[https://ouronet.com.br/wp-content/webp-expres...
10,"800 Mb 164,90",[https://ouronet.com.br/wp-content/webp-expres...
11,"800 Mb por apenas R$10,00 no combo! 129,90",[https://ouronet.com.br/wp-content/webp-expres...
12,"600 Mb por apenas R$15,00 no combo! 109,90",[https://ouronet.com.br/wp-content/webp-expres...
13,"+VENDIDO 300 Mb 99,90",[https://ouronet.com.br/wp-content/webp-expres...
14,80 Mb + bônus de 20 Mb *apenas na contratação ...,[https://ouronet.com.br/wp-content/webp-expres...
15,40 Mb + bônus de 20 Mb *apenas na contratação ...,[https://ouronet.com.br/wp-content/webp-expres...

In [5]:
# Extraindo urls das imagens
df_img = (
    df["svas"]
    .explode()
    .dropna()
    .drop_duplicates()
    .reset_index(drop=True)
    .to_frame(name="URL_IMAGEM")
)
df_img

                                          URL_IMAGEM
0  https://ouronet.com.br/wp-content/webp-express...
1  https://ouronet.com.br/wp-content/webp-express...
2  https://ouronet.com.br/wp-content/webp-express...
3  https://ouronet.com.br/wp-content/webp-express...
4  https://ouronet.com.br/wp-content/webp-express...

In [6]:
# Lendo informações das imagens
import requests
import base64

# Chave API Google - Pessoal Rangel
API_KEY = "AIzaSyA2QBWsoOKBIAg7gdp-OL2JqbK_TS3iXoU"

def extrair_texto_imagem(url):
    img = requests.get(url).content
    payload = {
        "requests": [{
            "image": {"content": base64.b64encode(img).decode()},
            "features": [{"type": "TEXT_DETECTION"}]
        }]
    }
    r = requests.post(f"https://vision.googleapis.com/v1/images:annotate?key={API_KEY}", json=payload)
    try:
        return r.json()["responses"][0]["fullTextAnnotation"]["text"]
    except:
        return None

df_img["texto"] = df_img["URL_IMAGEM"].apply(extrair_texto_imagem)
df_img

                                          URL_IMAGEM                texto
0  https://ouronet.com.br/wp-content/webp-express...        Apps\nPremium
1  https://ouronet.com.br/wp-content/webp-express...             + DEEZER
2  https://ouronet.com.br/wp-content/webp-express...       Apps\nStandard
3  https://ouronet.com.br/wp-content/webp-express...                + max
4  https://ouronet.com.br/wp-content/webp-express...  +\nRede (CO))\nMesh

## **2. Tratamento**

In [7]:
df_tratado = df.copy()

# Data e provedor
df_tratado["DATA"] = date.today().strftime("%Y-%m-%d")
df_tratado["ISP"] = "Ouronet"

# Velocidade
df_tratado["VELOCIDADE"] = (
    df_tratado["descricao"]
    .str.extract(r"(\d+)\s*mb", flags=re.IGNORECASE)[0]
    .astype(float)
)

# Preco
df_tratado["PRECO"] = (
    df_tratado["descricao"]
    .str.extract(r"(\d+[.,]\d{2})\s*$")[0]
    .str.replace(",", ".", regex=False)
    .astype(float)
)

# SVA
mapa_svas = dict(zip(df_img["URL_IMAGEM"], df_img["texto"]))
df_tratado["SVAs"] = (df_tratado["svas"].apply(lambda urls: ", ".join([mapa_svas[url] for url in urls if url in mapa_svas])))

df_tratado["SVAs"] = (
    df_tratado["SVAs"]
    .astype(str)
    .str.replace("\n", " ", regex=False)
)

#Seleção de colunas
df_tratado = df_tratado[["DATA", "ISP", "VELOCIDADE", "SVAs", "PRECO"]]

df_tratado

          DATA      ISP  VELOCIDADE                                SVAs  PRECO
0   2026-05-12  Ouronet       600.0              Apps Premium, + DEEZER  109.9
1   2026-05-12  Ouronet       300.0             Apps Standard, + DEEZER   99.9
2   2026-05-12  Ouronet        80.0                       Apps Standard   89.9
3   2026-05-12  Ouronet        40.0                       Apps Standard   79.9
4   2026-05-12  Ouronet       800.0  + max, + DEEZER, + Rede (CO)) Mesh  164.9
5   2026-05-12  Ouronet       800.0              Apps Premium, + DEEZER  129.9
6   2026-05-12  Ouronet       600.0              Apps Premium, + DEEZER  109.9
7   2026-05-12  Ouronet       300.0             Apps Standard, + DEEZER   99.9
8   2026-05-12  Ouronet        80.0                       Apps Standard   89.9
9   2026-05-12  Ouronet        40.0                       Apps Standard   79.9
10  2026-05-12  Ouronet       800.0  + max, + DEEZER, + Rede (CO)) Mesh  164.9
11  2026-05-12  Ouronet       800.0              Apps Premium, + DEEZER  129.9
12  2026-05-12  Ouronet       600.0              Apps Premium, + DEEZER  109.9
13  2026-05-12  Ouronet       300.0             Apps Standard, + DEEZER   99.9
14  2026-05-12  Ouronet        80.0                       Apps Standard   89.9
15  2026-05-12  Ouronet        40.0                       Apps Standard   79.9

## **3. Carga**

In [8]:
# Salvando
provedor = "OURONET.csv"
nome_arq = df_tratado["DATA"].max() + "-" + provedor

# Na rede Valenet
pasta = r"\\fileserver\arquivos\Estrategia Comercial\2. POWER BI\ECM - Radar Mercado\ScrapingPlanos"
df_tratado.to_csv(fr"{pasta}\{nome_arq}", index=False)

# Neste Workspace
df_tratado.to_csv(f"../../data/flat/{provedor}", index=False)

print(f"🟢 {nome_arq} salvo!")

🟢 2026-05-12-OURONET.csv salvo!