# **Scraping Planos Vivo**

_Página de planos do provedor: https://vivo.com.br/para-voce/produtos-e-servicos/para-casa/internet_

## **2 Tratamento**

### **2.1 Lista de códigos de produtos/promoções exibidas na página**

In [2]:
from bs4 import BeautifulSoup
from urllib.parse import parse_qs
import html

soup = BeautifulSoup(open("../../data/scraped/vivo.html", encoding="utf-8"), "html.parser")
planos_na_pagina = list({
    f'{q.get("productsIds", [""])[0]}|@|{q.get("promotion", [""])[0]}'
    for a in soup.find_all("a", href=True)
    if "vivofibra" in a["href"]
    for q in [parse_qs(html.unescape(a["href"]).split("?")[1])]
})
print(planos_na_pagina)

['235,327|@|', '105|@|GAMER', '106|@|', '317,329|@|Fibra100', '235,264|@|600', '235,266|@|600', '235,329|@|Fibra100', '235,267|@|600', '235,328|@|Fibra100', '317,328|@|Fibra100', '317,327|@|', '235|@|600', '2|@|Pro_160', '127|@|', '122|@|', '235,265|@|600', '106|@|GAMER', '105|@|', '117|@|']

### **2.2 Filtro: apenas planos na página**

In [3]:
import pandas as pd
df = pd.read_json("../../data/scraped/vivo.json")
df = df[
    (
        df["codigoDaOferta"].fillna("").astype(str)
        + "|@|"
        + df["codigoPromocional"].fillna("").astype(str)
    ).isin(planos_na_pagina)
]
df.head()

,ofertaMacro,ativa,nomeComercial,codigoDaOferta,codigoPromocional,steps,textoOferta,vivoTotal,vivoTotalV1V2,TV Solo?,...,Parceiro,Token carrinho abandonado homologação,Token pedido fechado homologação,Token carrinho abandonado produção,Token pedido fechado produção,Token Topaz homologação,Token Topaz produção,isRecorderEnable,isFibraParaTodos,ASBflag
0,Fibra solo,Sim,VIVO FIBRA 600 MEGA,235,600,4A,Pague 500 Mega e leve 600 Mega! Oferta exclusi...,Não,Não,Não,...,NaN,WxN9Dn2k%2BD0VDikuONhHTPM4oVHbK3HRpfu64bcDgHk,%2B%2F%2FD5Rh%2F3YH24CjFjc89L2X3lDDPCPN6i%2F9l...,F7jUlBR%2B%2FN22HP0QdnDuJubYzHXDsthq9xq5MVNFJUs,s8VdIt2CU0nFlrm7uBj%2Ba9tiBWCwi7RCMt2ONZYBXYo,7eXbzC9mPxv3W0TnTyLwV2l7f0BwDUQbBQZkbWndCRc,3rZQbrrKGnhAHIt672eqMmlmjoqSBbBMqHD0BRPKMbE,NaN,NaN,true
5,Fibra solo,Sim,VIVO FIBRA 700 MEGA,105,None,4A,NaN,Não,Não,Não,...,NaN,WxN9Dn2k%2BD0VDikuONhHTPM4oVHbK3HRpfu64bcDgHk,eGlLgtsWYhwoP%2BarehF6zquFqxVzrzjK5Jrqf5baC4E,F7jUlBR%2B%2FN22HP0QdnDuJubYzHXDsthq9xq5MVNFJUs,FohHYGq9BOouIFHRYDZ%2FiJga8dtgOuRKAUG1QZ0U14s,7eXbzC9mPxv3W0TnTyLwV2l7f0BwDUQbBQZkbWndCRc,3rZQbrrKGnhAHIt672eqMmlmjoqSBbBMqHD0BRPKMbE,NaN,NaN,true
6,Fibra solo,Sim,VIVO FIBRA 1 GIGA,106,None,4A,NaN,Não,Não,Não,...,NaN,WxN9Dn2k%2BD0VDikuONhHTPM4oVHbK3HRpfu64bcDgHk,eGlLgtsWYhwoP%2BarehF6zquFqxVzrzjK5Jrqf5baC4E,F7jUlBR%2B%2FN22HP0QdnDuJubYzHXDsthq9xq5MVNFJUs,FohHYGq9BOouIFHRYDZ%2FiJga8dtgOuRKAUG1QZ0U14s,7eXbzC9mPxv3W0TnTyLwV2l7f0BwDUQbBQZkbWndCRc,3rZQbrrKGnhAHIt672eqMmlmjoqSBbBMqHD0BRPKMbE,NaN,NaN,true
9,Fibra Gamer,Sim,VIVO FIBRA 700 MEGA + GAMER,105,GAMER,4A,NaN,Não,Não,Não,...,NaN,WxN9Dn2k%2BD0VDikuONhHTPM4oVHbK3HRpfu64bcDgHk,q%2F%2FaSXdgjV81etO%2FDjeenCQbOLA9S4uP5PC%2Ba5...,F7jUlBR%2B%2FN22HP0QdnDuJubYzHXDsthq9xq5MVNFJUs,cXE3bJELr2Do9ibAjAhh1%2Fi5R%2FN3URM7e%2BvzLz4pkxg,7eXbzC9mPxv3W0TnTyLwV2l7f0BwDUQbBQZkbWndCRc,3rZQbrrKGnhAHIt672eqMmlmjoqSBbBMqHD0BRPKMbE,NaN,NaN,true
10,Fibra Gamer,Sim,VIVO FIBRA 1 GIGA + GAMER,106,GAMER,4A,NaN,Não,Não,Não,...,NaN,WxN9Dn2k%2BD0VDikuONhHTPM4oVHbK3HRpfu64bcDgHk,q%2F%2FaSXdgjV81etO%2FDjeenCQbOLA9S4uP5PC%2Ba5...,F7jUlBR%2B%2FN22HP0QdnDuJubYzHXDsthq9xq5MVNFJUs,cXE3bJELr2Do9ibAjAhh1%2Fi5R%2FN3URM7e%2BvzLz4pkxg,7eXbzC9mPxv3W0TnTyLwV2l7f0BwDUQbBQZkbWndCRc,3rZQbrrKGnhAHIt672eqMmlmjoqSBbBMqHD0BRPKMbE,NaN,NaN,true

### **2.3 Tratamento das colunas de interesse**

In [4]:
from datetime import date
import re

# Data e provedor
df["DATA"] = date.today().strftime("%Y-%m-%d")
df["ISP"] = "Vivo"

# Velocidade
df["VELOCIDADE"] = df["textoFibra"].str.extract(r"(\d+)").astype(float)
df.loc[
    df["textoFibra"].str.contains(r"giga|gb|g\b", case=False, na=False, regex=True),
    "VELOCIDADE"
] *= 1000

# SVA: cria uma lista as colunas que iniciam com "cortesiaFibra" ou "sva" ou "textoTv"
# depois concatena essas colunas
cols_sva = [c for c in df if c.startswith(("cortesiaFibra", "sva", "textoTv"))]

df["SVAs"] = df[cols_sva].apply(
    lambda row: ", ".join(row.dropna().astype(str)),
    axis=1
)

# Preço
df["PRECO"] = (
    df["total"]
    .str.replace(r"[^\d,]", "", regex=True)
    .str.replace(",", ".", regex=False)
    .astype(float)
)

#Seleção de colunas
df_tratado = df[["DATA", "ISP", "VELOCIDADE", "SVAs", "PRECO"]]

df_tratado

,DATA,ISP,VELOCIDADE,SVAs,PRECO
0,2026-05-12,Vivo,600.0,Amazon Prime,100.0
5,2026-05-12,Vivo,700.0,Amazon Prime,150.0
6,2026-05-12,Vivo,1000.0,Amazon Prime,300.0
9,2026-05-12,Vivo,700.0,"Amazon Prime, Ponto Cabeado, Exit Lag",170.0
10,2026-05-12,Vivo,1000.0,"Amazon Prime, Ponto Cabeado, Exit Lag",320.0
11,2026-05-12,Vivo,500.0,"Amazon Prime, TV Avançado",270.0
13,2026-05-12,Vivo,700.0,"Amazon Prime, TV Avançado",320.0
14,2026-05-12,Vivo,1000.0,"Amazon Prime, TV Avançado",470.0
32,2026-05-12,Vivo,600.0,"Amazon Prime, Netflix Padrão",144.9
53,2026-05-12,Vivo,600.0,"Amazon Prime, Serviço de automonitoramento",120.0
54,2026-05-12,Vivo,600.0,"Amazon Prime, Serviço de automonitoramento + 3...",135.0
97,2026-05-12,Vivo,600.0,"Amazon Prime, TV Avançado, Netflix Padrão",314.9
121,2026-05-12,Vivo,500.0,Amazon Prime,160.0
223,2026-05-12,Vivo,600.0,"Amazon Prime, Globoplay Padrão",127.9
224,2026-05-12,Vivo,600.0,"Amazon Prime, Disney+ Padrão",143.9
225,2026-05-12,Vivo,600.0,"Amazon Prime, TV Avançado, Globoplay Padrão",298.9
227,2026-05-12,Vivo,600.0,"Amazon Prime, TV Avançado, Disney+ Padrão",313.9
229,2026-05-12,Vivo,600.0,Serviço de automonitoramento com 1 câmera 360º,124.9
230,2026-05-12,Vivo,600.0,Serviço de automonitoramento com 1 câmera 360º...,139.9

## **3. Carga**

In [5]:
# Salvando
provedor = "VIVO.csv"
nome_arq = df_tratado["DATA"].max() + "-" + provedor

# Na rede Valenet
pasta = r"\\fileserver\arquivos\Estrategia Comercial\2. POWER BI\ECM - Radar Mercado\ScrapingPlanos"
df_tratado.to_csv(fr"{pasta}\{nome_arq}", index=False)

# Neste Workspace
df_tratado.to_csv(f"../../data/flat/{provedor}", index=False)

print(f"🟢 {nome_arq} salvo!")

🟢 2026-05-12-VIVO.csv salvo!